CREATE TABLE IF NOT EXISTS Players(
  id INTEGER NOT NULL,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  price INTEGER,
  photo VARCHAR(255),
  dreamteam_count INTEGER,
  total_points INTEGER,
  points_per_game VARCHAR(255),
  position INTEGER,
  team INTEGER,
  minutes INTEGER,
  goals_scored INTEGER,
  assits INTEGER,
  clean_sheets INTEGER,
  goals_conceded INTEGER,
  own_goals INTEGER,
  penalties_saved INTEGER,
  penalties_misssed INTEGER,
  yellow_cards INTEGER,
  red_cards INTEGER,
  saves INTEGER,
  bonus INTEGER,
  PRIMARY KEY (id)
)

  /*
  "id": 285,
"photo": "66749.jpg",
"web_name": "Lukaku",
"team_code": 1,
"status": "a",
"code": 66749,
"first_name": "Romelu",
"second_name": "Lukaku",
"squad_number": 9,
"news": "",
"now_cost": 118,
"chance_of_playing_this_round": null,
"chance_of_playing_next_round": 100,
"value_form": "0.7",
"value_season": "4.2",
"cost_change_start": 3,
"cost_change_event": 0,
"cost_change_start_fall": -3,
"cost_change_event_fall": 0,
"in_dreamteam": true,
"dreamteam_count": 2,
"selected_by_percent": "59.4",
"form": "8.3",
"transfers_out": 487253,
"transfers_in": 994558,
"transfers_out_event": 106706,
"transfers_in_event": 70042,
"loans_in": 0,
"loans_out": 0,
"loaned_in": 0,
"loaned_out": 0,
"total_points": 50,
"event_points": 6,
"points_per_game": "7.1",
"ep_this": "9.3",
"ep_next": "8.3",
"special": false,
"minutes": 630,
"goals_scored": 7,
"assists": 1,
"clean_sheets": 6,
"goals_conceded": 2,
"own_goals": 0,
"penalties_saved": 0,
"penalties_missed": 1,
"yellow_cards": 1,
"red_cards": 0,
"saves": 0,
"bonus": 8,
"bps": 189,
"influence": "295.8",
"creativity": "164.3",
"threat": "457.0",
"ict_index": "91.8",
"ea_index": 0,
"element_type": 4,
"team": 12

   */